### ISSUE TITLE
Cx-Flow scan issues in Gitlab CI/CD pipelines

### ISSUE THREAD

**Issue by rsutar31** [checkmarx-ts/cx-flow#85]
->We have integrated Cx-Flow scan with Gitlab CI/CD pipeline. Even after marking few HIGH vulnerabilities as Not exploitable in Cx Console, Gitlab CI/CD pipeline fails. We are using Cx-Flow version of 1.5.4 (latest version). 
->We also added flag break-build=true (as suggested by Support Engineer) and tested it again. But its still failing.

**Comment by kmcdon83** [comment]
@rsutar31 we are investigating your issue.

**Comment by alex-ko-dev** [comment]
Hello @rsutar31 
To help us investigate the issue, could you please provide the following:
1. CxFlow logs (at Debug level) with the error message.
2. CxFlow command line that you use.
3. Your CxFlow configuration?

To enable debug logging, please add the following section to the config file:

```
logging:
  file:
    name: cx-flow.log
  level:
    com:
      checkmarx: DEBUG
    org:
      apache:
        http:
          wire: TRACE
      springframework:
        web:
          client:
            RestTemplate: TRACE
```

As a temporary workaround, you can add the following to the config file:

```
cx-flow:
  break-build: false
```

Thanks,
Alexey
